CREATE DATABASE PINGPONG;
USE PINGPONG;

CREATE TABLE INFORMACION (
	NOMBRE VARCHAR(25) NOT NULL,
    ALIAS VARCHAR(25) NOT NULL,
    EDAD INT NOT NULL,
    CIUDAD VARCHAR(25) NOT NULL,
    LIGA VARCHAR(20) NOT NULL,
    LATERALIDAD VARCHAR(20) NOT NULL,
    GOLPE_ESTRELLA VARCHAR (25) NOT NULL,
    ATAQUE VARCHAR(3) NOT NULL,
    DEFENSA VARCHAR(3) NOT NULL,
    GIF VARCHAR(30) NOT NULL,
    GRITO VARCHAR(40) NOT NULL,
    CONSTRAINT PK_INFORMACION PRIMARY KEY (ALIAS)
);

/* INFO VICTOR */
INSERT INTO INFORMACION (NOMBRE, ALIAS, EDAD, CIUDAD, LIGA, LATERALIDAD, GOLPE_ESTRELLA, ATAQUE, DEFENSA, GIF, GRITO)  
VALUES ('VICTOR', 'MACHINEGUN', 23, 'MEMBRILLA', 'MADERA', 'DIESTRO', 'ZUMO BIFRUTAS', '3/5', '3/5', '/gifs/victor.gif', 'src/sonido/VICTOR.wav');

/* INFO  JESUS */
INSERT INTO INFORMACION (NOMBRE, ALIAS, EDAD, CIUDAD, LIGA, LATERALIDAD, GOLPE_ESTRELLA, ATAQUE, DEFENSA, GIF, GRITO)  
VALUES ('JESUS', 'MISIL', 20, 'MANZANARES', 'DIAMANTE', 'DIESTRO', 'MISIL NO LOOK', '3/5', '5/5', '/gifs/Jesus.gif', 'src/sonido/jesus.wav');

/* INFO  PACO */
INSERT INTO INFORMACION (NOMBRE, ALIAS, EDAD, CIUDAD, LIGA, LATERALIDAD, GOLPE_ESTRELLA, ATAQUE, DEFENSA, GIF, GRITO)  
VALUES ('PACO', 'FILONGO', 28, 'MANZANARES', 'DIAMANTE', 'DIESTRO', 'LA BURRAQUEN', '3/5', '4/5', '/gifs/paco.gif', 'src/sonido/paco.wav');

/* INFO  CARLOS */
INSERT INTO INFORMACION (NOMBRE, ALIAS, EDAD, CIUDAD, LIGA, LATERALIDAD, GOLPE_ESTRELLA, ATAQUE, DEFENSA, GIF, GRITO)  
VALUES ('CARLOS', 'CARLITUS', 19, 'MEMBRILLA', 'MADERA', 'DIESTRO', 'REMATE SIGILOSO', '2/5', '3/5', '/gifs/carlos.gif', 'src/sonido/carlos.wav');

/* INFO  DAVID */
INSERT INTO INFORMACION (NOMBRE, ALIAS, EDAD, CIUDAD, LIGA, LATERALIDAD, GOLPE_ESTRELLA, ATAQUE, DEFENSA, GIF, GRITO)  
VALUES ('DAVID', 'RED', 22, 'LA SOLANA', 'DIAMANTE', 'DIESTRO', 'MUERE', '4/5', '4/5', '/gifs/david.gif', 'src/sonido/david.wav');

/* INFO  MAESO */
INSERT INTO INFORMACION (NOMBRE, ALIAS, EDAD, CIUDAD, LIGA, LATERALIDAD, GOLPE_ESTRELLA, ATAQUE, DEFENSA, GIF, GRITO)  
VALUES ('ANTONIO', 'MAESO', 27, 'MANZANARES', 'FUMADORES', 'DIESTRO', 'FUMAQUINHA', '0/5', '0/5', '/gifs/maeso.gif', 'src/sonido/maeso.wav');

/* INFO  MANUEL */
INSERT INTO INFORMACION (NOMBRE, ALIAS, EDAD, CIUDAD, LIGA, LATERALIDAD, GOLPE_ESTRELLA, ATAQUE, DEFENSA, GIF, GRITO)  
VALUES ('MANUEL', 'EL BICHO', 20, 'BOLAÑOS', 'DIAMANTE', 'DIESTRO', 'EL FUHRER', '3/5', '5/5', '/gifs/manuel.gif', 'src/sonido/manuel.wav');

/* INFO  TONY */
INSERT INTO INFORMACION (NOMBRE, ALIAS, EDAD, CIUDAD, LIGA, LATERALIDAD, GOLPE_ESTRELLA, ATAQUE, DEFENSA, GIF, GRITO)  
VALUES ('ANTONIO EDUARDO', 'TONY', 19, 'LA SOLANA', 'MADERA', 'DIESTRO', 'DIABLO SHOT', '2/5', '3/5', '/gifs/tony.gif', 'src/sonido/tony.wav');

CREATE TABLE REGISTER (
	USUARIO VARCHAR(25) NOT NULL,
    CONTRASEÑA VARCHAR(25) NOT NULL,
    CONSTRAINT PK_REGISTER PRIMARY KEY (USUARIO)
);

SELECT * FROM INFORMACION